const fs = require('fs');
const path = require('path');

const OUTPUT_EN = 'Data/feats/en/feats.ts';
const OUTPUT_ES = 'Data/feats/es/feats.ts';

let out = `import { Ability, Skill, DetailData, SubclassData } from '../../types';

// AUTO-GENERATED from docs/Manual/03-feats.md
// Do not edit manually - regenerate with: node generate-feats.cjs

export interface Feat {
  name: string;
  description: string;
}

`;

const feats = [
  // Origin Feats - Common
  { name: "Alert", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Initiative Proficiency.** When you roll Initiative, you can add your Proficiency Bonus to the roll.\n**Initiative Swap.** Immediately after you roll Initiative, you can swap your Initiative with the Initiative of one willing ally in the same combat." },
  { name: "Crafter", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Tool Proficiency.** You gain proficiency with three Artisan's Tools of your choice.\n**Discount.** Whenever you buy a nonmagical item, you receive a 20 percent discount on it.\n**Fast Crafting.** When you finish a Long Rest, you can craft one piece of gear. The item lasts until you finish another Long Rest." },
  { name: "Healer", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Healing.** When you use a Healer's Kit to stabilize a dying creature, you also give that creature 1d6 Hit Points.\n**Surgical Skill.** As a Bonus Action, you can use a Healer's Kit to tend to a creature's wounds. The creature regains Hit Points equal to 1d6 + your Proficiency Bonus." },
  { name: "Lucky", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Luck Points.** You have a number of Luck Points equal to your Proficiency Bonus.\n**Advantage.** When you roll a d20 for a D20 Test, you can spend 1 Luck Point to give yourself Advantage on the roll.\n**Disadvantage.** When a creature rolls a d20 for an attack roll against you, you can spend 1 Luck Point to impose Disadvantage on that roll." },
  { name: "Magic Initiate", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Two Cantrips.** You learn two cantrips from the Cleric, Druid, or Wizard spell list.\n**Level 1 Spell.** Choose a level 1 spell. You always have that spell prepared. You can cast it once without a spell slot, and you regain the ability when you finish a Long Rest.\n**Repeatable.** You can take this feat more than once, but you must choose a different spell list each time." },
  { name: "Musician", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Instrument Training.** You gain proficiency with three Musical Instruments of your choice.\n**Encouraging Song.** As you finish a Short or Long Rest, you can play a song and give Heroic Inspiration to allies who hear it. The number of allies equals your Proficiency Bonus." },
  { name: "Savage Attacker", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Rage Damage.** When you roll damage for a melee weapon attack, you can reroll the weapon's damage dice and use either total. This property can be used a number of times equal to your Proficiency Bonus, and you regain your expended uses when you finish a Long Rest." },
  { name: "Skilled", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain proficiency in three skills of your choice, or you gain expertise in one skill." },
  { name: "Tavern Brawler", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Improvised Weapon.** A weapon you use for an improvised attack has a +1 bonus to attack rolls, and deals 1d4 damage.\n**Grappler.** You have Advantage on attack rolls against a creature you are Grappling.\n**Unarmed Strike.** Your Unarmed Strikes deal 1d4 damage, and you have the Grappling Fighting Style." },
  { name: "Tough", category: "Origin Feat", description: "Category: Origin Feat\nPrerequisite: None\n\nBenefit: Your Hit Point maximum increases by an amount equal to twice your level when you gain this feat, and then increases by 2 Hit Points whenever you gain a level." },
  // Origin Feats - Faerun
  { name: "Cult of the Dragon Initiate", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You have joined the Cult of the Dragon.\n**Draconic Spell.** You learn the Thunderwave spell and can cast it at 2nd level without using a spell slot.\n**Dark One's Blessing.** When you reduce a creature to 0 Hit Points, you gain temporary Hit Points equal to your Proficiency Bonus." },
  { name: "Emerald Enclave Fledgling", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You are a fledgling member of the Emerald Enclave.\n**Natural Recovery.** As a Bonus Action, you can regain a spell slot of level 1 or 2. Once you use this benefit, you can't use it again until you finish a Long Rest.\n**Reactive.** When a creature you can see moves within 30 feet of you, you can take a Reaction to make an Opportunity Attack." },
  { name: "Harper Agent", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You are an agent of the Harpers.\n**Harper's Eye.** You have Advantage on Insight and Perception checks.\n**Spellcasting.** You learn the Detect Magic spell and can cast it as a Ritual." },
  { name: "Lords' Alliance Agent", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You are an agent of the Lords' Alliance.\n**Political Mimicry.** You have Advantage on Deception checks to pass as a member of a different noble house.\n**Silver Tongue.** You have Proficiency in Persuasion." },
  { name: "Purple Dragon Rook", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You are a member of the Purple Dragon.\n**Shield Bearer.** When an ally within 5 feet of you is attacked, you can use your Reaction to impose Disadvantage on the attack roll.\n**Retribution.** When you use your Shield Bearer benefit, you can make a melee attack against the attacker as part of the same Reaction." },
  { name: "Spellfire Spark", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You have been touched by spellfire.\n**Spellfire Adept.** You learn the Eldritch Blast cantrip and can cast it as a 2nd-level spell.\n**Spellfire Healing.** As a Bonus Action, you can touch a creature and restore Hit Points equal to your Proficiency Bonus." },
  { name: "Tyro of the Gauntlet", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: Level 4+, Strength or Dexterity 13+\n\nBenefit: You are a newcomer to the fighting styles.\n**Fighting Style.** You gain a Fighting Style feat.\n**Unarmored Defense.** While you aren't wearing armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier." },
  { name: "Zhentarim Ruffian", category: "Origin Feat (Faerun)", description: "Category: Origin Feat (Faerun)\nPrerequisite: None\n\nBenefit: You are a member of the Zhentarim.\n**Dark Traveler.** You have Advantage on Stealth checks in dim light and darkness.\n**Snake Oil Salesman.** You have Proficiency in Deception and Persuasion." },
  // Origin Feats - Exotic
  { name: "Child of the Sun", category: "Origin Feat (Exotic)", description: "Category: Origin Feat (Exotic)\nPrerequisite: None\n\nBenefit: You have been blessed by the sun.\n**Sun's Blessing.** You have Resistance to Radiant damage.\n**Light Bearer.** You can cast the Light cantrip at will." },
  { name: "Shadowmoor Hexer", category: "Origin Feat (Exotic)", description: "Category: Origin Feat (Exotic)\nPrerequisite: None\n\nBenefit: You have been touched by the shadows of Shadowmoor.\n**Shadow Step.** As a Bonus Action, you can teleport up to 30 feet to an unoccupied space in dim light or darkness.\n**Umbral Form.** While in dim light or darkness, you can take the Hide action as a Bonus Action." },
  { name: "Tireless Reveler", category: "Origin Feat (Exotic)", description: "Category: Origin Feat (Exotic)\nPrerequisite: None\n\nBenefit: You are a creature of endless party.\n**Endless Endurance.** You have Advantage on Constitution saving throws.\n**Partier.** You have Proficiency in Performance and Persuasion." },
  { name: "Vampire Hunter", category: "Origin Feat (Exotic)", description: "Category: Origin Feat (Exotic)\nPrerequisite: None\n\nBenefit: You hunt the undead.\n**Vampire Slayer.** You have Advantage on attack rolls against Vampires.\n**Hunter's Sense.** You can sense the presence of undead within 60 feet of you." },
  { name: "Vampire's Plaything", category: "Origin Feat (Exotic)", description: "Category: Origin Feat (Exotic)\nPrerequisite: None\n\nBenefit: You have been touched by a Vampire.\n**Vampire's Blessing.** You have Resistance to Necrotic damage.\n**Undead Weakness.** You have Vulnerability to Radiant damage." },
  // General Feats - Common
  { name: "Ability Score Improvement", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+\n\nBenefit: Increase one ability score of your choice by 2, or increase two ability scores of your choice by 1. This feat can't increase an ability score above 20.\n**Repeatable.** You can take this feat more than once." },
  { name: "Actor", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Charisma score by 1, to a maximum of 20.\n**Impersonation.** You have Proficiency in Deception and Performance. In addition, when you impersonate someone else, you have Advantage on Deception checks to conceal your identity." },
  { name: "Athlete", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Climber.** You have a Climb Speed equal to your Speed.\n**Jump.** You have Advantage on Strength (Athletics) checks made to jump, and you don't fall damage if you fall less than 20 feet." },
  { name: "Charger", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Charge Attack.** If you move at least 10 feet in a straight line before hitting the Attack action, you gain a +2 bonus to the attack's damage roll, or you can make an extra attack as part of the same action." },
  { name: "Chef", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Constitution or Wisdom score by 1, to a maximum of 20.\n**Prepare Feast.** When you finish a Long Rest, you can prepare a feast for up to six people. The feast takes 1 hour to complete, and the creatures who eat the feast gain 1d8 Hit Points, and they can't have the Poisoned condition for 24 hours." },
  { name: "Crossbow Expert", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Dexterity 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Ignore Loading.** You ignore the Loading property of Hand Crossbow, Heavy Crossbow, and Light Crossbow.\n**Firing in Melee.** Being within 5 feet of an enemy doesn't impose Disadvantage on your attack rolls with crossbows.\n**Dual Wielding.** When you make the extra attack of the Light property, you can add your ability modifier to the damage of the extra attack if that attack is with a crossbow that has the Light property." },
  { name: "Crusher", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Temporal.** When you hit a creature with an attack that deals bludgeoning damage, you can move the creature 5 feet to an unoccupied space.\n**Sundering Strike.** When you hit a creature with a weapon attack, you can deal extra damage equal to your Proficiency Bonus." },
  { name: "Defensive Duelists", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Dexterity 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Parry.** When a creature attacks you and you are wielding a melee weapon, you can use your reaction to add your Proficiency Bonus to your Armor Class for that attack." },
  { name: "Dual Wielder", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Strength or Dexterity 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Enhanced Dual Wielding.** When you take the Attack action and attack with a weapon with the Light property, you can make one extra attack as a Bonus Action later on the same turn with a different weapon.\n**Quick Draw.** You can draw or stow two weapons that lack the Two-Handed property." },
  { name: "Durable", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Constitution score by 1, to a maximum of 20.\n**Forceful.** When you roll a Hit Point Die to regain Hit Points, you can reroll the die and use either total.\n**Stay Down.** When you have the Unconscious condition, you can make a DC 10 Constitution saving throw to stabilize yourself." },
  { name: "Elemental Adept", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Spellcasting or Pact Magic Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Elemental Mastery.** Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. Your spells of that element ignore Resistance to damage of that type.\n**Elemental Cantrip.** When you select this feat, you learn one cantrip of the chosen element." },
  { name: "Fey Touched", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+\n\nBenefit: Your exposure to the Feywild's magic grants you the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Fey Magic.** Choose one level 1 spell from the Divination or Enchantment school. You always have that spell and Misty Step prepared. You can cast each spell once without a spell slot, regaining the ability when you finish a Long Rest." },
  { name: "Grappler", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Strength 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength score by 1, to a maximum of 20.\n**Grappler.** You have Advantage on attack rolls against a creature you are Grappling.\n**Pin.** When you have a creature Grappled, you can use your action to deal 1d6 damage to the creature." },
  { name: "Great Weapon Master", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Strength 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength score by 1, to a maximum of 20.\n**Heavy Weapon Mastery.** When you hit a creature with a weapon that has the Heavy property as part of the Attack action, you can cause the weapon to deal extra damage equal to your Proficiency Bonus.\n**Hew.** Immediately after you score a Critical Hit or reduce a creature to 0 Hit Points with a melee weapon, you can make one attack with the same weapon as a Bonus Action." },
  { name: "Heavily Armored", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Medium Armor Proficiency\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength score by 1, to a maximum of 20.\n**Armor Training.** You gain training with Heavy armor." },
  { name: "Heavy Armor Master", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Heavy Armor Proficiency\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength score by 1, to a maximum of 20.\n**Resilient.** While wearing Heavy armor, you have Resistance to bludgeoning, piercing, and slashing damage from nonmagical attacks." },
  { name: "Inspiring Leader", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Charisma score by 1, to a maximum of 20.\n**Inspiring Presence.** As a Bonus Action, you can grant yourself and up to five friendly creatures within 30 feet temporary Hit Points equal to your level + your Charisma modifier." },
  { name: "Keen Mind", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence score by 1, to a maximum of 20.\n**Memory.** You have Advantage on Intelligence (Investigation) and Wisdom (Survival) checks.\n**Know-it-all.** You can take the Search action as a Bonus Action." },
  { name: "Lightly Armored", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Armor Training.** You gain training with Light armor." },
  { name: "Mage Slayer", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Mage Hunter.** When a creature within 5 feet of you casts a spell, you can make an Opportunity Attack against the creature." },
  { name: "Martial Weapon Training", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Weapon Training.** You gain training with all Martial weapons." },
  { name: "Medium Armor Master", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Medium Armor Proficiency\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Armor Training.** You gain training with Medium armor.\n**Dexterous.** When you wear Medium armor, you can add your Dexterity modifier to your Armor Class." },
  { name: "Moderately Armored", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Light Armor Proficiency\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Armor Training.** You gain training with Medium armor and Shields." },
  { name: "Mounted Combatant", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Mounted Fighter.** While you are mounted, you have Advantage on attack rolls against creatures that are Small or smaller.\n**Unseat.** When you hit a creature while mounted and the creature is your size or smaller, you can force the creature to make a Strength saving throw or be knocked Prone." },
  { name: "Observant", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence or Wisdom score by 1, to a maximum of 20.\n**Quick Study.** You have Proficiency in Investigation and Perception. In addition, you can take the Search action as a Bonus Action." },
  { name: "Piercer", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Sundering Strike.** When you hit a creature with a weapon that deals piercing damage, you can deal extra damage equal to your Proficiency Bonus.\n**Critical.** When you roll a 20 on a d20 for an attack roll with a piercing weapon, you can roll an extra damage die." },
  { name: "Poisoner", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence or Dexterity score by 1, to a maximum of 20.\n**Poisonous Attack.** When you hit a creature with a weapon attack, you can deal extra poison damage equal to your Proficiency Bonus.\n**Poison Master.** You have Proficiency with poisoner's supplies, and you have Resistance to poison damage." },
  { name: "Polearm Master", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Polearm Attack.** When you take the Attack action and attack with a weapon that has the Heavy and Reach properties, you can use your Bonus Action to make a melee attack with the opposite end of the weapon.\n**Lunge.** When you make a melee attack with a polearm, you can deal extra damage equal to your Proficiency Bonus." },
  { name: "Resilient", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 20.\n**Save Proficiency.** Gain Proficiency in the saving throw of the ability increased." },
  { name: "Ritual Caster", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Spellcasting or Pact Magic Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Ritual Adept.** You know three spells with the Ritual tag, and you can cast them as Rituals without preparing them." },
  { name: "Sentinel", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Strength or Dexterity 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Guardian.** Immediately after a creature within 5 feet of you takes the Disengage action or hits a target other than you, you can make an Opportunity Attack against that creature.\n**Halt.** When you hit a creature with an Opportunity Attack, the creature's Speed becomes 0 for the rest of the current turn." },
  { name: "Shadow Touched", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+\n\nBenefit: Your exposure to the Shadowfell's magic grants you the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Shadow Magic.** Choose one level 1 spell from the Illusion or Necromancy school. You always have that spell and Invisibility prepared. You can cast each spell once without a spell slot, regaining the ability when you finish a Long Rest." },
  { name: "Sharpshooter", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Dexterity 13+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Bypass Cover.** Your ranged attacks ignore Half Cover and Three-Quarters Cover.\n**Firing in Melee.** Being within 5 feet of an enemy doesn't impose Disadvantage on your attack rolls with ranged weapons.\n**Long Shots.** Attacking at long range doesn't impose Disadvantage on your attack rolls with ranged weapons." },
  { name: "Shield Master", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Shield Bash.** When you take the Attack action, you can use your Bonus Action to make a shield bash.\n**Protection.** When you are wielding a Shield, you have +2 bonus to AC." },
  { name: "Skill Expert", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase one ability score of your choice by 1, to a maximum of 20.\n**Skill Expertise.** Choose one skill in which you have Proficiency. Your Proficiency Bonus doubles for ability checks with that skill." },
  { name: "Skulker", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Hide in Plain Sight.** You can attempt to Hide as a Bonus Action, and you can do so even when only lightly obscured." },
  { name: "Slasher", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Sundering Strike.** When you hit a creature with a weapon that deals slashing damage, you can reduce the creature's Speed by 10 feet until the start of your next turn.\n**Critical.** When you roll a 20 on a d20 for an attack roll with a slashing weapon, you can roll an extra damage die." },
  { name: "Speedy", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Hustle.** You can take the Dash action as a Bonus Action.\n**Second Wind.** As a Bonus Action, you can regain Hit Points equal to 1d10 + your Proficiency Bonus." },
  { name: "Spell Sniper", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Spellcasting or Pact Magic Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Bypass Cover.** Your ranged spell attacks ignore Half Cover and Three-Quarters Cover.\n**War Caster.** You have Advantage on Constitution saving throws made to maintain Concentration." },
  { name: "Telekinetic", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Minor Telekinesis.** You learn the Mage Hand spell. You can cast it without Verbal or Somatic components, you can make the spectral hand Invisible, and its range increases by 30 feet.\n**Telekinetic Shove.** As a Bonus Action, you can telekinetically shove one creature you can see within 30 feet." },
  { name: "Telepathic", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Telepathy.** You can communicate telepathically with creatures within 60 feet of you.\n**Sense Thoughts.** You can cast Detect Thoughts once per Long Rest." },
  { name: "War Caster", category: "General Feat", description: "Category: General Feat\nPrerequisite: Level 4+, Spellcasting or Pact Magic Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Intelligence, Wisdom, or Charisma score by 1, to a maximum of 20.\n**Concentration.** You have Advantage on Constitution saving throws made to maintain Concentration.\n**Reactive Spell.** When a creature provokes an Opportunity Attack, you can take a Reaction to cast a spell at the creature.\n**Somatic Components.** You can perform the Somatic components of spells even when you have weapons or a Shield in one or both hands." },
  { name: "Weapon Master", category: "General Feat", description: "Category: General Feat\nPrerequisite: None\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Weapon Proficiency.** You gain Proficiency with four weapons of your choice.\n**Mastery.** Choose one weapon you are proficient with. That weapon gains a Mastery property of your choice." },
  // Fighting Style Feats
  { name: "Archery", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Dexterity score by 1, to a maximum of 20.\n**Far Shot.** When you make a ranged attack, the attack's range increases by 50 percent.\n**Precision.** When you make a ranged attack, you can add your Proficiency Bonus to the attack roll." },
  { name: "Blind Fighting", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Constitution or Wisdom score by 1, to a maximum of 20.\n**Blindsight.** You have Blindsight out to 30 feet.\n**Wave the Darkness.** As a Bonus Action, you can cast Darkness. Once you use this property, you can't use it again until you finish a Long Rest." },
  { name: "Defense", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Armor Training.** You gain training with all armor.\n**Defensive Coordination.** While you are wearing armor, you have +2 bonus to AC." },
  { name: "Dueling", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Parry.** When an attack reduces you to 0 Hit Points, you can make a melee weapon attack against the attacker as a Bonus Action." },
  { name: "Great Weapon Fighting", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength score by 1, to a maximum of 20.\n**Cleave.** When you reduce a creature to 0 Hit Points with a melee weapon, you can make another attack with the same weapon against a different creature." },
  { name: "Interception", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Constitution score by 1, to a maximum of 20.\n**Interception.** When a creature within 5 feet of you takes damage, you can use your Reaction to reduce the damage by 1d10 + your Proficiency Bonus." },
  { name: "Protection", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Guardian.** When a creature within 5 feet of you attacks a target other than you, you can impose Disadvantage on the attack roll." },
  { name: "Thrown Weapon Fighting", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Quick Throw.** When you make a ranged attack with a thrown weapon, you can draw the weapon as part of the attack.\n**Returning Weapon.** When you make a ranged attack with a thrown weapon, you can add your ability modifier to the damage." },
  { name: "Two Weapon Fighting", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Enhanced Dual Wielding.** When you take the Attack action and attack with a weapon with the Light property, you can make one extra attack as a Bonus Action." },
  { name: "Unarmed Fighting", category: "Fighting Style Feat", description: "Category: Fighting Style Feat\nPrerequisite: Fighting Style Feature\n\nBenefit: You gain the following benefits.\n**Ability Score Increase.** Increase your Strength or Dexterity score by 1, to a maximum of 20.\n**Unarmed Mastery.** Your Unarmed Strikes deal 1d6 damage, and you have the Grappling Fighting Style." },
  // Epic Boon Feats
  { name: "Boon of Combat Prowess", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Mastery.** Choose one weapon you are proficient with. That weapon gains a Mastery property of your choice." },
  { name: "Boon of Dimensional Travel", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Dimensional Step.** As a Bonus Action, you can cast Dimension Door. Once you use this property, you can't use it again until you finish a Long Rest." },
  { name: "Boon of Energy Resistance", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Energy Resistance.** Choose one damage type: Acid, Cold, Fire, Lightning, or Thunder. You have Resistance to that damage type." },
  { name: "Boon of Fate", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Luck Points.** You have 3 Luck Points. When you make a d20 Test, you can spend 1 point to roll an extra d20. You can choose which result to use." },
  { name: "Boon of Fortitude", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Hit Points.** Your Hit Point maximum increases by 30.\n**Regeneration.** You regain 5 Hit Points at the start of each of your turns if you have at least 1 Hit Point." },
  { name: "Boon of Irresistible Offense", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Bypass.** Your weapon attacks ignore Resistance to the damage type dealt by the weapon." },
  { name: "Boon of Recovery", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Second Wind.** As a Bonus Action, you can regain Hit Points equal to 1d10 + your level. You can use this property twice, and you regain your expended uses when you finish a Long Rest." },
  { name: "Boon of Skill", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Skill Expertise.** Choose three skills. You have Expertise in those skills." },
  { name: "Boon of Speed", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Speed Increase.** Your Speed increases by 30 feet.\n**Dash.** You can take the Dash action as a Bonus Action." },
  { name: "Boon of Spell Recall", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Spell Recovery.** You can cast any spell of level 8 or lower without spending a spell slot. Once you use this property, you can't use it again for 1 minute." },
  { name: "Boon of the Night Spirit", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Etherealness.** As an action, you can cast Etherealness for 10 minutes. Once you use this property, you can't use it again until you finish a Long Rest." },
  { name: "Boon of Truesight", category: "Epic Boon Feat", description: "Epic Boon (Level 19+).\n\nBenefit: **Truesight.** You have Truesight out to 60 feet." },
  // Dragonmark Feats
  { name: "Aberrant Dragonmark", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Aberrant Spell.** You learn one cantrip and one level 1 spell from the Psionics spell list.\n**Aberrant Resistance.** You have Resistance to psychic damage." },
  { name: "Mark of Detection", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Detection Magic.** You learn the Detect Magic and Detect Thoughts spells.\n**Eyes of the Finder.** As a Bonus Action, you can sense the presence of any Humanoid within 30 feet." },
  { name: "Mark of Finding", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Finding Magic.** You learn the Detect Magic and Locate Object spells.\n**Finder's Sense.** As a Bonus Action, you can sense the presence of any Beast or Plant within 30 feet." },
  { name: "Mark of Handling", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Animal Friendship.** You learn the Animal Friendship spell and can cast it as a Ritual.\n**Wild Speaker.** You can communicate with Beasts." },
  { name: "Mark of Healing", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Healing Magic.** You learn the Cure Wounds and Healing Word spells.\n**Healer's Sense.** As a Bonus Action, you can sense the presence of any creature within 30 feet that has 0 Hit Points." },
  { name: "Mark of Hospitality", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Hospitality Magic.** You learn the Detect Poison and Purify Food and Drink spells.\n**Guest Friend.** You have Proficiency in Persuasion." },
  { name: "Mark of Making", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Maker's Magic.** You learn the Identify and Mending spells.\n**Crafting Sense.** As a Bonus Action, you can identify the properties of a magic item within 30 feet." },
  { name: "Mark of Passage", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Passage Magic.** You learn the Misty Step and Pass without Trace spells.\n**Safe Passage.** You have Advantage on saving throws to avoid or end the Poisoned condition." },
  { name: "Mark of Scribing", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Scribing Magic.** You learn the Comprehend Languages and Message spells.\n**Scribe's Sense.** As a Bonus Action, you can detect the presence of any written message within 30 feet." },
  { name: "Mark of Sentinel", category: "Dragonmark Feat", description: "Dragonmark Feat.\n\nBenefit: **Sentinel Magic.** You learn the Blade Ward and Sanctuary spells.\n**Sentinel's Alert.** You have Advantage on Initiative checks." },
];

out += "export const FEATS_EN: Feat[] = [\n";
feats.forEach(f => {
  const desc = f.description.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  out += `  { name: "${f.name.replace(/"/g, '\\"')}", description: "${desc}" },
`;
});
out += "];\n";

fs.writeFileSync(OUTPUT_EN, out, "utf8");
console.log(`Written to ${OUTPUT_EN} with ${feats.length} feats`);

// Write same data to ES folder as placeholder
fs.writeFileSync(OUTPUT_ES, out, "utf8");
console.log(`Written to ${OUTPUT_ES} with ${feats.length} feats (placeholder - needs Spanish data)`);
